//
//  FavoriteItem.swift
//  thecoffeelinks-native-swift
//
//  Favorite item with exact product+customization configuration and user notes
//

import Foundation

/// A favorited product with exact customization and personal notes
struct FavoriteItem: Codable, Identifiable, Hashable {
    let id: UUID
    let product: Product
    let customization: OrderCustomization
    var notes: [FavoriteNote]
    let createdAt: Date
    var lastOrderedAt: Date?
    var orderCount: Int
    
    init(product: Product, customization: OrderCustomization, notes: [FavoriteNote] = []) {
        self.id = UUID()
        self.product = product
        self.customization = customization
        self.notes = notes
        self.createdAt = Date()
        self.lastOrderedAt = nil
        self.orderCount = 0
    }
    
    /// Unique key for matching favorites
    var matchKey: String {
        let toppingsStr = customization.toppings?.sorted().joined(separator: ",") ?? ""
        return "\(product.id)|\(customization.size)|\(customization.sugar ?? "")|\(customization.ice ?? "")|\(toppingsStr)"
    }
    
    /// Display name with size
    var displayName: String {
        var name = product.name
        if customization.size != "M" && customization.size != "Medium" {
            name += " (\(customization.size))"
        }
        return name
    }
    
    /// Price for this configuration
    var priceForSize: Double {
        guard let options = product.sizeOptions else { return 0 }
        switch customization.size.lowercased() {
        case "s", "small": return options.small.price
        case "m", "medium": return options.medium.price
        case "l", "large": return options.large.price
        default: return options.medium.price
        }
    }
    
    /// Active notes (for display during checkout)
    var activeNotes: [FavoriteNote] {
        notes.filter { $0.isActive }
    }
    
    /// Display string of all active notes
    var notesDisplay: String? {
        let active = activeNotes
        guard !active.isEmpty else { return nil }
        return active.map { $0.text }.joined(separator: " • ")
    }
    
    // Hashable
    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }
    
    static func == (lhs: FavoriteItem, rhs: FavoriteItem) -> Bool {
        lhs.id == rhs.id
    }
}

/// A personal note attached to a favorite
struct FavoriteNote: Codable, Identifiable, Hashable {
    let id: UUID
    var text: String // Max 140 chars
    var isActive: Bool // Whether to show during checkout
    var isAutoGenerated: Bool // True if AI created this
    let createdAt: Date
    
    init(text: String, isAutoGenerated: Bool = false) {
        self.id = UUID()
        self.text = String(text.prefix(140))
        self.isActive = true
        self.isAutoGenerated = isAutoGenerated
        self.createdAt = Date()
    }
}

/// Context for AI predictions
struct PredictionContext: Codable {
    let timeSlot: TimeSlot
    let dayOfWeek: Int // 1-7, Sunday = 1
    let weather: WeatherCondition?
    let isWeekend: Bool
    let hourOfDay: Int
    
    init(date: Date = Date(), weather: WeatherCondition? = nil) {
        let calendar = Calendar.current
        let hour = calendar.component(.hour, from: date)
        
        self.hourOfDay = hour
        self.dayOfWeek = calendar.component(.weekday, from: date)
        self.isWeekend = dayOfWeek == 1 || dayOfWeek == 7
        self.weather = weather
        
        if hour < 11 {
            self.timeSlot = .morning
        } else if hour < 17 {
            self.timeSlot = .afternoon
        } else {
            self.timeSlot = .evening
        }
    }
}

enum TimeSlot: String, Codable, CaseIterable {
    case morning   // 6-11am
    case afternoon // 11am-5pm
    case evening   // 5pm+
}

enum WeatherCondition: String, Codable {
    case hot
    case cold
    case rainy
    case normal
    
    var prefersHotDrinks: Bool {
        self == .cold || self == .rainy
    }
    
    var prefersColdDrinks: Bool {
        self == .hot
    }
}

/// Extended address with delivery-specific fields
struct DeliveryAddress: Codable, Identifiable, Hashable {
    let id: String
    var label: String // "Home", "Work", custom
    var fullAddress: String
    var coordinates: Coordinates?
    var isDefault: Bool
    var deliveryNotes: String?
    var isInDeliveryZone: Bool
    let createdAt: Date
    var lastUsedAt: Date?
    var usageCount: Int // For ranking by most-used
    
    struct Coordinates: Codable, Hashable {
        let latitude: Double
        let longitude: Double
    }
    
    init(id: String = UUID().uuidString, label: String, fullAddress: String, isDefault: Bool = false) {
        self.id = id
        self.label = label
        self.fullAddress = fullAddress
        self.isDefault = isDefault
        self.isInDeliveryZone = true // Default true, server validates
        self.createdAt = Date()
        self.lastUsedAt = nil
        self.coordinates = nil
        self.deliveryNotes = nil
        self.usageCount = 0
    }
}
